version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: Vignesh@2858
      POSTGRES_DB: instagram

  app:
    build: .
    ports:
      - '5000:5000'
    depends_on:
      - db

